- app/Resources/views/full/home.html.twig
- app/Resources/views/pagelayout.html.twig
- app/config/ezplatform.yml
https://jira.ez.no/browse/COM-19888 Create a frontpage content type
> COM-19888: frontpage content type

- app/Resources/views/pagelayout.html.twig
- app/Resources/views/pagelayout_footer.html.twig
- app/config/config.yml
- app/config/config_ezplatform_com.yml
- app/config/parameters.yml.dist
- src/AppBundle/Controller/SiteController.php
$this->ping( @SylvainGuittard );
> Controller, template, and parameters file for rendering content

- app/config/views.yml
- src/AppBundle/Controller/DownloadController.php
https://jira.ez.no/browse/COM-19919
> COM-19919: Public methods in controller classes should only be actions

- app/Resources/views/pagelayout_footer.html.twig
jira issue: https://jira.ez.no/browse/COM-19925
> COM-19925: update footer

- composer.lock
https://jira.ez.no/browse/COM-19949
> COM-19949: [Insight] - A Symfony application should be bootable

- web/assets/css/ezplatform-com.css
jira issue: https://jira.ez.no/browse/COM-19951
> COM-19951: [Buttons] - Text is not visible

- README.md
https://jira.ez.no/browse/COM-19965
> COM-19965: Add Insight badge to the readme file

- app/Resources/views/full/blog_post.html.twig
- web/assets/css/blog_post.css
https://jira.ez.no/browse/COM-19969
> COM-19969: Mobile View Margins 0

- README.md
- app/Resources/views/composer/install.html.twig
- app/config/services/installer.yml
- src/AppBundle/Installer/AppInstaller.php
Fix #54 
Should be merged after #60
This PR adds an installer which will download data from ezplatform daily backups.
Manually from a fresh install
> #54 app installer

- web/assets/css/blog.css
- web/assets/css/blog_post.css
- web/assets/css/ezplatform-com.css
jira issue: https://jira.ez.no/browse/COM-19983
> COM-19983: Update CSS for blog post

- app/config/config_ezplatform_page.yml
- web/assets/css/error.css
- web/assets/css/ezplatform-com.css
- web/assets/css/responsive.css
jira issue: https://jira.ez.no/browse/COM-19987
- Added styles for outline buttons
- Adjusted the height of the page
- Reordered the CSS files (responsive.css should be loaded at the end)
> COM-19987: 404 page CSS adjustments

- web/assets/css/article.css
- web/assets/css/ezplatform-com.css
jira issue: https://jira.ez.no/browse/COM-19982
> COM-19982: Update headings

- app/Resources/views/full/bundle_list.html.twig
> COM-19990: fix load more button

- web/assets/css/embed.css
JIRA issue: [https://jira.ez.no/browse/COM-20007](https://jira.ez.no/browse/COM-20007)
CSS code was changed to make Embed Code filename visually identical to Image caption.
> COM-20007: Design improvements for embed code

- src/AppBundle/Controller/DownloadController.php
- src/AppBundle/QueryType/LatestReleasesQueryType.php
Fixed bug with incorrect release version sorting in Download Table.
> Fix: Download Table sorting

- app/Resources/views/full/bundle_list.html.twig
- app/Resources/views/line/bundle_card.html.twig
- app/config/config_ezplatform_page.yml
- app/config/routing.yml
- app/config/services/controller.yml
- app/config/services/packagist.yml
- app/config/services/twig.yml
- composer.json
- src/AppBundle/Command/UpdateBundlesListCommand.php
- src/AppBundle/Controller/BundleController.php
- src/AppBundle/Form/OrderType.php
- src/AppBundle/Form/SearchType.php
- src/AppBundle/QueryType/BundlesQueryType.php
- src/AppBundle/Service/Packagist/PackagistServiceProvider.php
- src/AppBundle/Service/Packagist/PackagistServiceProviderInterface.php
- web/assets/css/bundle.css
- web/assets/css/bundles_list.css
- web/assets/js/app.js
**JIRA issues**: 
1. [https://jira.ez.no/browse/COM-20002](https://jira.ez.no/browse/COM-20002)
2. [https://jira.ez.no/browse/COM-20010](https://jira.ez.no/browse/COM-20010)
3. [https://jira.ez.no/browse/COM-20011](https://jira.ez.no/browse/COM-20011)
This PR contains design changes ordered in mentioned JIRA issue.
| Field name | Field ID | Type | Required | Searchable | Translatable |
|-------------|--------|------|----------|------------|--------------|
| Bundle ID | bundle_id | ezstring | Yes | Yes | No |
| Name | name | ezstring | No | Yes | Yes |
| Description | description | ezrichtext | Yes | Yes | Yes |
| Packagist URL | packagist_url | ezurl | Yes | No | No |
| Downloads | downloads | ezinteger | No | Yes | No |
| Stars | stars | ezinteger | No | Yes | No |
| Forks | forks | …
> COM-20002: Bundles Design improvements

- app/Resources/views/full/bundle_list.html.twig
- web/assets/css/bundles_list.css
This PR fixes issue with displaying bundle name on the mobile version of ezplatform.com.
> Fix: displaying package name on mobile

- src/AppBundle/Service/Packagist/PackagistServiceProvider.php
https://jira.ez.no/browse/COM-20016
> COM-20016: Warning when trying to render Bundles list

- app/config/routing.yml
- composer.json
- src/AppBundle/Controller/BundleController.php
- src/AppBundle/Controller/TagController.php
- src/AppBundle/QueryType/BundlesQueryType.php
JIRA issue: [https://jira.ez.no/browse/COM-20020](https://jira.ez.no/browse/COM-20020)
Fixed issues:
1. [https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=violations#532291469](https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=violations#532291469)
2. [https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=violations#532291468](https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=violations#532291468)
3. [https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=violations#532291472](https://insight.sensiolabs.com/projects/389976fc-bc12-4596-b29f-1e66cde269b6/analyses/13?status=v …
> COM-20020: Fix issues indicated in SensioLabsInsight for ezplatform.com

- src/AppBundle/Installer/AppInstaller.php
https://jira.ez.no/browse/COM-20015
> COM-20015: timeout for `tar` process on installation command

- web/assets/css/discourse_header_footer.css
- web/assets/css/discourse_main.css
jira issue: https://jira.ez.no/browse/COM-20026
> COM-20026: Improve CSS for Discourse

- src/AppBundle/Command/UpdateBundlesListCommand.php
> Fix: bundle list search query limit

- web/assets/css/discourse_header_footer.css
This PR fixes inconsistency in header design between Discuss and other ezplatform.com pages.
> Fix Discuss CSS

- composer.json
- composer.lock
This hotfix solves 500 error on the bundle list.
> Fix PackagistAPI client issue

- web/assets/js/app.js
https://jira.ez.no/browse/COM-20038
> COM-20038: Google Analytics tracking for ezplatform.com

- web/assets/js/app.js
https://jira.ez.no/browse/COM-20046
> COM-20046: Downloading GA event for Beta doesn't work

- app/Resources/views/themes/ezplatform/full/bundle_list.html.twig
- app/Resources/views/themes/ezplatform/parts/bundle_list/list.html.twig
- app/config/routing.yml
- app/config/services/pagerfanta.yml
- src/AppBundle/Controller/BundleController.php
- src/AppBundle/Form/BundleOrderType.php
- src/AppBundle/Form/BundleSearchType.php
- src/AppBundle/View/Template/BundlesListTemplate.php
- web/assets/js/app.js
- web/assets/scss/bundles_list.scss
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [COM-20045](https://jira.ez.no/browse/COM-20045)
| **Bug**| yes
| **New feature**    | no
This PR depends on: https://github.com/ezsystems/ezplatform-com/pull/135
Pagination design was changed a little bit as discussed with Nikita.
> COM-20045: Some bundles appear twice on ezplatform.com

- app/Resources/views/themes/ezplatform/full/product_feedback.html.twig
- app/config/config_ezplatform_page.yml
- app/config/views.yml
jira ticket: https://jira.ez.no/browse/COM-20058
> COM-20058: Add product feedback portal

- app/Resources/views/themes/ezplatform/line/blog_post.html.twig
jira: https://jira.ez.no/browse/COM-20060
> COM-20060: responsive images for blog post

- app/Resources/views/themes/ezplatform/embed/image.html.twig
- web/assets/scss/ezplatform-com.scss
jira: https://jira.ez.no/browse/COM-20062
> COM-20062: blog post design improvements

- app/config/config_ezplatform_page.yml
- app/config/services/controller.yml
- src/AppBundle/Controller/BundleController.php
- src/AppBundle/QueryType/BundlesQueryType.php
https://jira.ez.no/browse/COM-20053
> COM-20053: category fix

- app/Resources/translations/custom_tags.en.yaml
- app/Resources/views/themes/ezplatform/fields/ezrichtext/custom_tags/ezyoutube.html.twig
- app/config/custom_tags.yml
- app/config/services/twig.yml
- src/AppBundle/Twig/YoutubeIdExtractorExtension.php
- web/assets/scss/custom_tags.scss
- web/assets/scss/page.scss
https://jira.ez.no/browse/COM-20085
> COM-20085: Add Youtube Custom tag to ezplatform.com

- app/Resources/views/themes/ezplatform/full/package.html.twig
- app/config/services/command.yml
- src/AppBundle/Command/UpdatePackageListCommand.php
- src/AppBundle/Service/Cache/CacheService.php
- src/AppBundle/Service/Cache/CacheServiceInterface.php
- web/assets/scss/package.scss
https://jira.ez.no/browse/COM-20087
> COM-20087: Package page bugfixes

- app/config/config_ezplatform_page.yml
- app/config/services/service.yml
- app/config/services/validator.yml
- src/AppBundle/Service/AbstractService.php
- src/AppBundle/Service/Package/PackageService.php
- src/AppBundle/Validator/Constraints/PackageDbNotExistsConstraintValidator.php
- web/assets/scss/ezplatform-com.scss
https://jira.ez.no/browse/COM-20083
> COM-20083: Package submission page (Permission Fix)

- app/Resources/views/themes/ezplatform/row/download_section.html.twig
https://jira.ez.no/browse/COM-20102
> COM-20102: "/admin" in the URL for uploaded releases

- app/Resources/views/themes/ezplatform/layout/footer.html.twig
https://jira.ez.no/browse/SITE-21054
> SITE-21054: Update social medias

- app/Resources/views/themes/ezplatform/row/download_section.html.twig
- app/config/config_ezplatform_page.yml
- app/config/default_parameters.yml
- app/config/services/controller.yml
- app/config/services/twig.yml
- src/AppBundle/Controller/DownloadController.php
- src/AppBundle/Twig/AppConfigExtension.php
https://jira.ez.no/browse/COM-20112
> COM-20112: Betas are not displayed on download list after publish

- app/config/views.yml
- src/AppBundle/Service/DOM/DOMService.php
- src/AppBundle/Service/Package/PackageService.php
- src/AppBundle/Service/PackageRepository/GitHubService.php
- src/AppBundle/Service/PackageRepository/GitLabService.php
- src/AppBundle/Url/UrlBuilder.php
- src/AppBundle/ValueObject/RepositoryMetadata.php
- web/assets/scss/package.scss
> Fixed absolute URLs generation for GitLab packages

- src/AppBundle/Service/PackageRepository/GitHubService.php
https://jira.ez.no/browse/COM-20117
> COM-20117: Change GitHub authorization method
